### PR TITLE
Suggestion for some helpers to avoid common bottlenecks

### PR DESCRIPTION
**Pull request by cdiener**
This is a proposal to add helpers to get all row/column primal/duals in one go from the C level as well as helper functions that convert Python lists to the required int/doubleArray types.

Easier to understand with some examples (sorry for using cobrapy here, just makes it easier to construct a test problem):

```Python
In [1]: from cobra.test import create_test_model

In [2]: mod = create_test_model("textbook")

In [3]: mod.optimize()
Out[3]: <Solution 0.874 at 0x7efd06db6fd0>

In [4]: %time mod.solver.optimize()
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 230 µs
Out[4]: 'optimal'

In [5]: import swiglpk

In [6]: %time x = mod.solver.primal_values
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 1.24 ms

In [7]: %time y = swiglpk.get_col_primals(mod.solver.problem)
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 41.2 µs

In [8]: sum(abs(x-y) for x, y in zip(x.values(), y))
Out[8]: 0.0

In [9]: def to_ia(x):
   ...:     ia = swiglpk.intArray(len(x))
   ...:     for i in range(len(x)): ia[i] = x[i]
   ...:     

In [10]: li = list(range(10000))

In [11]: %time ia = to_ia(li)
CPU times: user 16 ms, sys: 0 ns, total: 16 ms
Wall time: 17.4 ms

In [12]: %time ia = swiglpk.as_intArray(li)
CPU times: user 4 ms, sys: 0 ns, total: 4 ms
Wall time: 314 µs

```

Basically getting all primals/duals at onces is about 100x faster than iterating them in Python, and more importantly, is also faster than resolving the model.

Constructing large input arrays from Python lists directly in C is also much faster than doing it in Python.

### CODE REVIEW

**Comment by hredestig** [comment]
looks like a nice speedup!

**Comment by Midnighter** [comment]
I don't know how it works in Swig but Cython also allows one to construct numpy array like views on memory arrays. That'd avoid the need to even copy the values into a Python list. On the downside one would have to take care of the memory management... so maybe not worth it.

**Comment by KristianJensen** [comment]
Does this also get the primals for integer variables? Glpk has two different functions `glp_get_col_val` and `glp_mip_col_val` for continuous and integer variables, respectively.

**Comment by KristianJensen** [comment]
@cdiener I just tested this with a MIP problem. For integer variables `get_col_primals` returns an incorrect value. If you fix this I'll be happy to implement this in optlang's glpk_interface.

**Comment by cdiener** [comment]
@KristianJensen yes sorry, didn't expect that to get merged so quickly :open_mouth: Will fix that. There are functions in glpk that can tell me whether a row/col is integer/double right?

@Midnighter yes and I think if you warp it around the numpy array the array takes over memory management. There is also the numpy.i typemap that converts many input arg types to numpy types. Hower, numpy is currently not a requirement for swiglpk, optlang or cobrapy so...

**Pull request merged**
