### PR TITLE
Update CI

### LINKED ISSUE #49: Remove Python 2 support
Python 2 has now been deprecated. Consequently, Microsoft has now [removed the downloads for Visual Studio for Python 2.7](https://cibuildwheel.readthedocs.io/en/stable/cpp_standards/#windows-and-python-27) which is required to build swiglpk on Python 2.7 on Windows. This is what makes the automated builds fail.

Users that require Python 2.7 versions can still use the previous versions of swiglpk that support it.

### LINKED ISSUE #51: fails to install in python 3.10
**edit:** the below was with python 3.10.0. It works fine with 3.9.7.

Not sure this is something you can address, but [GitHub Actions](https://github.com/SysBioChalmers/yeast-GEM/runs/3967864108?check_suite_focus=true#step:4:250) fails to install `swiglpk 5.0.3`:

```python
pip install -r requirements/ci-requirements.txt
[...]
ERROR: Could not find a version that satisfies the requirement swiglpk==5.0.3 (from versions: 0.1.0, 1.0.0, 1.2.12, 1.2.13, 1.2.14, 1.4.4, 1.5.0b0, 1.5.0, 1.5.1, 4.64.0b0, 4.65.0, 4.65.1, 5.0.0)
ERROR: No matching distribution found for swiglpk==5.0.3
```
where `ci-requirements.txt` contains:
```python
swiglpk==5.0.3
    # via
    #   cobra
    #   optlang
```

Meanwhile, forcing version 5.0.0 in `ci-requirements.txt` [results](https://github.com/edkerk/yeast-GEM/runs/4450708188?check_suite_focus=true#step:4:251) in:

```python
Collecting swiglpk==5.0.0
  Downloading swiglpk-5.0.0.tar.gz (32 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /opt/hostedtoolcache/Python/3.10.0/x64/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-39pg8iv7/swiglpk_e7c0d6367e9b4cc9b9ebc51e1af871d9/setup.py'"'"'; __file__='"'"'/tmp/pip-install-39pg8iv7/swiglpk_e7c0d6367e9b4cc9b9ebc51e1af871d9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-wkn7cwwj
       cwd: /tmp/pip-install-39pg8iv7/swiglpk_e7c0d6367e9b4cc9b9ebc51e1af871d9/
  Complete output (12 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-39pg8iv7/swiglpk_e7c0d6367e9b4cc9b9ebc51e1af871d9/setup.py", line 52, in <module>
      glpk_header_dirname = find_glpk_header()
    File "/tmp/pip-install-39pg8iv7/swiglpk_e7c0d6367e9b4cc9b9ebc51e1af871d9/setup.py", line 35, in find_glpk_header
      glpsol_dirname = os.path.dirname(subprocess.check_output(['which', 'glpsol']))
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/subprocess.py", line 420, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/subprocess.py", line 524, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['which', 'glpsol']' returned non-zero exit status 1.
  Trying to determine glpk.h location
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/9b/49/260f20672b1f11138e240df219deb496ab9d17a5b8f623334b7e49e1e089/swiglpk-5.0.0.tar.gz#sha256=7b1e30bc401ab1ed638253ac93da5757d47247bce390b0e614b6cddb8838d1f7 (from https://pypi.org/simple/swiglpk/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement swiglpk==5.0.0 (from versions: 0.1.0, 1.0.0, 1.2.12, 1.2.13, 1.2.14, 1.4.4, 1.5.0b0, 1.5.0, 1.5.1, 4.64.0b0, 4.65.0, 4.65.1, 5.0.0)
ERROR: No matching distribution found for swiglpk==5.0.0
```

### PR DESCRIPTION
**Pull request by cdiener**
This updates the CI to the newest cibuildwheel.

- fixes #51 
- fixes #49

### CODE REVIEW

**Comment by Midnighter** [comment]
Updating to `joerick/cibuildwheel@v2.3.1` includes building for Python 3.10? Changes look good to me if that's the case.

**Comment by cdiener** [comment]
It does, but not sure why it's no trunning the CI here, maybe the repo owner has to enable it for me (new manual confirmation required for first time contributors, even though I contributed before).

**Review by Midnighter — APPROVED** [review]

**Comment by cdiener** [comment]
This was a bit quick. There are still some other fixes that are needed i think.

**Comment by Midnighter** [comment]
My bad.

**Pull request merged**
