### PR TITLE
Add source distribution

### PR DESCRIPTION
**Pull request by cdiener**
This adds a source distribution to the packaging.

### CODE REVIEW

**Comment by Midnighter** [comment]
Can you say two words about why creating the sdist on Mac is better/required?

**Comment by cdiener** [comment]
Just trying to find a way that works. All our existing scripts are specific to manylinux builds (CentOS) and won't work on the Ubuntu runners and I didn't want to reinvent the wheel (accidental pun here).

**Review by Midnighter — APPROVED** [review]
Looks reasonable. Should probably also be uploaded to PyPI and not only GitHub, right?

**Comment by cdiener** [comment]
I think it should right, because it downloads all artifacts into `./wheelhouse` and then sends the entire folder with twine. But maybe I got that wrong.

**Comment by Midnighter** [comment]
I missed that part 👍🏼

**Pull request merged**
